version: "3"

volume:
  node_modules:

services:
  main:
    build: .
    image: kazuki-m/main
    working_dir: /code
    volumes:
      - .:/code
      - node_modules:/code/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
